name: Publish
on:
  push:
    tags:
      - v*
      
jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - pair:
              elixir: "1.15"
              otp: "26.0"
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@main
        with:
          otp-version: ${{matrix.pair.otp}}
          elixir-version: ${{matrix.pair.elixir}}
          version-type: strict
      - uses: actions/cache@v3
        with:
          path: deps
          key: mix-deps-${{ hashFiles('**/mix.lock') }}

      - run: mix deps.get
      - run: HEX_API_KEY=${{ secrets.HEX_API_KEY }} mix hex.publish --yes
